version: '3'

services:
  db:
    build:
      context: ./DB
    environment:
      MYSQL_DATABASE: morgan
      MYSQL_USER: root
      MYSQL_PASSWORD: your_password
      MYSQL_ROOT_PASSWORD: your_password
    volumes:
      - ./DB/database_backup.sql:/docker-entrypoint-initdb.d/database_backup.sql
    ports:
      - 3306:3306

  api:
    build:
      context: ./API
    ports:
      - 8080:8080
    depends_on:
      - db
